# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: efficient_paper.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'efficient_paper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65\x66\x66icient_paper.proto\x12\x0f\x65\x66\x66icient_paper\"\xf9\x01\n\tPaperInfo\x12%\n\x05paper\x18\x01 \x01(\x0b\x32\x16.efficient_paper.Paper\x12)\n\x03pub\x18\x02 \x01(\x0b\x32\x1c.efficient_paper.Publication\x12#\n\x04\x63ode\x18\x03 \x01(\x0b\x32\x15.efficient_paper.Code\x12#\n\x04note\x18\x04 \x01(\x0b\x32\x15.efficient_paper.Note\x12)\n\x07keyword\x18\x05 \x01(\x0b\x32\x18.efficient_paper.Keyword\x12%\n\x05\x63over\x18\x06 \x01(\x0b\x32\x16.efficient_paper.Cover\"g\n\x05Paper\x12\x1a\n\x05title\x18\x01 \x01(\t:\x0bpaper title\x12\x0e\n\x04\x61\x62\x62r\x18\x02 \x01(\t:\x00\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x04 \x03(\t\x12\x14\n\x0cinstitutions\x18\x05 \x03(\t\"1\n\x0bPublication\x12\x14\n\x05where\x18\x01 \x01(\t:\x05\x61rXiv\x12\x0c\n\x04year\x18\x02 \x01(\x05\"*\n\x04\x43ode\x12\x15\n\x04type\x18\x01 \x01(\t:\x07Pytorch\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x1c\n\x04Note\x12\x14\n\x03url\x18\x01 \x01(\t:\x07note.md\"\x14\n\x05\x43over\x12\x0b\n\x03url\x18\x01 \x01(\t\"\xdc\x02\n\x07Keyword\x12,\n\x05words\x18\x01 \x03(\x0e\x32\x1d.efficient_paper.Keyword.Word\"\xa2\x02\n\x04Word\x12\x08\n\x04none\x10\x01\x12\x12\n\x0esparse_pruning\x10\x02\x12\x10\n\x0cquantization\x10\x03\x12\n\n\x06survey\x10\x04\x12\x0c\n\x08low_rank\x10\x05\x12\n\n\x06\x66usion\x10\x06\x12\x08\n\x04tool\x10\x07\x12\x0c\n\x08kv_cache\x10\x08\x12\x0c\n\x08training\x10\t\x12\x14\n\x10structure_design\x10\n\x12\x0c\n\x08sampling\x10\x0b\x12\x13\n\x0fweight_sparsity\x10\x0c\x12\x17\n\x13\x61\x63tivation_sparsity\x10\r\x12\x16\n\x12\x61ttention_sparsity\x10\x0e\x12\x17\n\x13structured_sparsity\x10\x0f\x12\x0e\n\ndeployment\x10\x10\x12\x0b\n\x07working\x10\x64\"P\n\nSearchWord\x12\x18\n\x10\x62\x61\x63kground_words\x18\x01 \x03(\t\x12\x11\n\tkey_words\x18\x02 \x03(\t\x12\x15\n\rexclude_words\x18\x03 \x03(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'efficient_paper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAPERINFO']._serialized_start=43
  _globals['_PAPERINFO']._serialized_end=292
  _globals['_PAPER']._serialized_start=294
  _globals['_PAPER']._serialized_end=397
  _globals['_PUBLICATION']._serialized_start=399
  _globals['_PUBLICATION']._serialized_end=448
  _globals['_CODE']._serialized_start=450
  _globals['_CODE']._serialized_end=492
  _globals['_NOTE']._serialized_start=494
  _globals['_NOTE']._serialized_end=522
  _globals['_COVER']._serialized_start=524
  _globals['_COVER']._serialized_end=544
  _globals['_KEYWORD']._serialized_start=547
  _globals['_KEYWORD']._serialized_end=895
  _globals['_KEYWORD_WORD']._serialized_start=605
  _globals['_KEYWORD_WORD']._serialized_end=895
  _globals['_SEARCHWORD']._serialized_start=897
  _globals['_SEARCHWORD']._serialized_end=977
# @@protoc_insertion_point(module_scope)
